- name: server install
  tags: server
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      with_items:
        - nginx
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - wget
        - gcc
        - make
