- name: server tuneup
  tags: tune
  hosts: all
  remote_user: isucon
  sudo: yes
  tasks:
    - name: nginx
      synchronize: src=server/etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
      notify: restart nginx
    - sysctl: name=net.ipv4.ip_local_port_range value="1024 65535" state=present
    - sysctl: name=net.ipv4.tcp_max_tw_buckets value="2000000" state=present
    - sysctl: name=net.core.somaxconn value="32768" state=present
    - sysctl: name=net.ipv4.tcp_tw_reuse value="1" state=present
    - sysctl: name=net.ipv4.tcp_tw_recycle value="1" state=present
    - sysctl: name=net.ipv4.tcp_fin_timeout value="10" state=present
    - name: systemd isucon
      synchronize: src=server/etc/systemd/system/isucon.service dest=/etc/systemd/system/isucon.service
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

- name: app setting
  tags: app
  hosts: all
  remote_user: isucon
  tasks:
    - synchronize: src=home/init.sh dest=/home/isucon/ mode=a+x
    - synchronize: src=home/env.sh dest=/home/isucon/ mode=a+x
    - synchronize: src=home/benchmarker dest=/home/isucon/ mode=a+x
    - synchronize: src=home/sql dest=/home/isucon/ 
    - synchronize: src=home/webapp dest=/home/isucon/ 

